apiVersion: apps/v1
kind: Deployment
metadata:
  name: crudmailsender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crudmailsender
  template:
    metadata:
      labels:
        app: crudmailsender
    spec:
      containers:
      - name: crudmailsender
        image: crud-mailsender:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 7004
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ASPNETCORE_HTTP_PORTS
          value: "7004"
        - name: RabbitSettings__Host
          value: rabbitmq
        - name: RabbitSettings__Username
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: username
        - name: RabbitSettings__Password
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: password
        - name: SMTPConfig__Server
          valueFrom:
            secretKeyRef:
              name: smtp-secret
              key: server
        - name: SMTPConfig__Port
          valueFrom:
            secretKeyRef:
              name: smtp-secret
              key: port
        - name: SMTPConfig__Username
          valueFrom:
            secretKeyRef:
              name: smtp-secret
              key: username
        - name: SMTPConfig__Password
          valueFrom:
            secretKeyRef:
              name: smtp-secret
              key: password
        - name: SMTPConfig__From
          valueFrom:
            secretKeyRef:
              name: smtp-secret
              key: mailfrom
---
apiVersion: v1
kind: Service
metadata:
  name: crudmailsender
spec:
  ports:
  - name: http
    protocol: TCP
    port: 7004
    targetPort: 7004
  selector:
    app: crudmailsender
