apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud-api
  template:
    metadata:
      labels:
        app: crud-api
    spec:
      containers:
      - name: crud-api
        image: crud-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 7002
          hostPort: 7002
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ASPNETCORE_HTTP_PORTS
          value: "7002"
        - name: MongoDbSettings__ConnectionString
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: connectionString
        - name: MongoDbSettings__DatabaseName
          value: TestDb
        - name: RabbitSettings__Host
          value: rabbitmq
        - name: RabbitSettings__Username
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: username
        - name: RabbitSettings__Password
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: crud-api
spec:
  ports:
  - name: http
    protocol: TCP
    port: 7002
    targetPort: 7002
  selector:
    app: crud-api
